version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mongo-network

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/checkpoint04_rm93688
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm start
    networks:
      - mongo-network

volumes:
  mongo-data:

networks:
  mongo-network:
